# Generated by Django 5.1.2 on 2024-12-08 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionFinance', '0001_initial'),
        ('gestionParrainage', '0002_remove_enfant_id_parrain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banque',
            name='id_centre',
            field=models.ForeignKey(default=455, on_delete=django.db.models.deletion.CASCADE, to='gestionParrainage.centre_orphelinat'),
            preserve_default=False,
        ),
    ]
