# Generated by Django 5.1.2 on 2024-12-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionFinance', '0002_banque_id_centre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banque',
            name='montant_crediter',
        ),
        migrations.RemoveField(
            model_name='banque',
            name='montant_debiter',
        ),
        migrations.AddField(
            model_name='banque',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='banque',
            name='type_operation',
            field=models.CharField(choices=[('Débit', 'Débit'), ('Crédit', 'Crédit')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='type_operation',
            field=models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sorties')], max_length=100),
        ),
    ]
