# Generated by Django 5.1.2 on 2024-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionFinance', '0003_remove_banque_montant_crediter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banque',
            name='type_operation',
            field=models.CharField(choices=[('Débit', 'Débit'), ('Crédit', 'Crédit')], default='Crédit', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='type_operation',
            field=models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sorties')], default='Entrée', max_length=100),
        ),
    ]
