# Generated by Django 5.1.2 on 2024-11-24 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre_Orphelinat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=100)),
                ('contact1', models.CharField(max_length=25)),
                ('contact2', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('localisation', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='../Centres')),
                ('responsable', models.CharField(blank=True, max_length=55)),
                ('date_creation', models.DateField()),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_par', models.CharField(max_length=60)),
                ('adresse_par', models.CharField(max_length=55)),
                ('contact_par', models.CharField(max_length=35)),
                ('email_par', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_enf', models.CharField(max_length=65)),
                ('prenom_enf', models.CharField(max_length=65)),
                ('date_admission', models.DateField()),
                ('sexe_enf', models.CharField(max_length=35)),
                ('statut_enf', models.CharField(max_length=250)),
                ('photo_enf', models.ImageField(upload_to='../Enfants')),
                ('date_naissance', models.DateField()),
                ('profession_enf', models.CharField(max_length=100)),
                ('lieu_naissance', models.CharField(max_length=65)),
                ('pere_enf', models.CharField(max_length=64)),
                ('mere_enf', models.CharField(max_length=60)),
                ('id_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionParrainage.centre_orphelinat')),
                ('id_parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionParrainage.parrain')),
            ],
        ),
        migrations.CreateModel(
            name='Dons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_dons', models.CharField(max_length=10)),
                ('date_don', models.DateField(auto_now=True)),
                ('description_don', models.CharField(max_length=100)),
                ('montant_don', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionParrainage.centre_orphelinat')),
                ('id_parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionParrainage.parrain')),
            ],
        ),
    ]
