# Generated by Django 5.1.2 on 2024-12-05 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionParrainage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfant',
            name='id_parrain',
        ),
        migrations.AlterField(
            model_name='centre_orphelinat',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/Centres'),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='photo_enf',
            field=models.ImageField(upload_to='media/Enfants'),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='sexe_enf',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=35),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='statut_enf',
            field=models.CharField(choices=[('Orphelin de Père', 'Orphelin de Père'), ('Orphelin de Mère', 'Orphelin de Mère'), ('Adopté', 'Adopté')], max_length=250),
        ),
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_parrainage', models.DateField(auto_now=True)),
                ('id_enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionParrainage.enfant')),
                ('id_parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionParrainage.parrain')),
            ],
        ),
    ]
