# Generated by Django 5.1.2 on 2024-12-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionParrainage', '0002_remove_enfant_id_parrain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='photo_enf',
            field=models.FileField(blank=True, upload_to='media/Enfants'),
        ),
    ]
