# Generated by Django 5.1.2 on 2024-12-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionParrainage', '0003_alter_enfant_photo_enf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='sexe_enf',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Sélectionner', max_length=35),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='statut_enf',
            field=models.CharField(choices=[('Orphelin de Père', 'Orphelin de Père'), ('Orphelin de Mère', 'Orphelin de Mère'), ('Adopté', 'Adopté')], default='Sélectionner', max_length=250),
        ),
    ]
