# Generated by Django 5.1.2 on 2024-12-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionParrainage', '0004_alter_enfant_sexe_enf_alter_enfant_statut_enf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='sexe_enf',
            field=models.CharField(choices=[('Sélectionner', 'Sélectionner un sexe'), ('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Sélectionner', max_length=35),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='statut_enf',
            field=models.CharField(choices=[('Sélectionner', 'Sélectionner un statut'), ('Orphelin de Père', 'Orphelin de Père'), ('Orphelin de Mère', 'Orphelin de Mère'), ('Adopté', 'Adopté')], default='Sélectionner', max_length=250),
        ),
    ]
