# Generated by Django 5.1.2 on 2024-12-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionParrainage', '0005_alter_enfant_sexe_enf_alter_enfant_statut_enf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='statut_enf',
            field=models.CharField(choices=[('Sélectionner', 'Sélectionner un statut'), ('Orphelin de Père', 'Orphelin de Père'), ('Orphelin de Mère', 'Orphelin de Mère'), ('Adopté', 'Adopté'), ('Orphelin Père/Mère', 'Orphelin Père/Mère')], default='Sélectionner', max_length=250),
        ),
    ]
