# Generated by Django 5.1.2 on 2024-11-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionParrainage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_bes', models.CharField(max_length=100)),
                ('type_bes', models.CharField(max_length=80)),
                ('date_bes', models.DateField(auto_now=True)),
                ('id_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionParrainage.centre_orphelinat')),
            ],
        ),
    ]
