# Generated by Django 5.1.2 on 2024-12-12 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBesoin', '0001_initial'),
        ('gestionParrainage', '0005_alter_enfant_sexe_enf_alter_enfant_statut_enf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoins',
            name='id_centre',
            field=models.ForeignKey(default='Sélectionner', on_delete=django.db.models.deletion.CASCADE, to='gestionParrainage.centre_orphelinat'),
        ),
    ]
