# Generated by Django 5.1.2 on 2024-12-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivites', '0002_alter_activites_id_centre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activites',
            old_name='date_debut',
            new_name='date_act',
        ),
        migrations.RemoveField(
            model_name='activites',
            name='date_fin',
        ),
    ]
