# Generated by Django 5.1.2 on 2024-12-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionActivites', '0003_rename_date_debut_activites_date_act_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activites',
            name='rapport_act',
            field=models.FileField(blank=True, upload_to='media/Rapport'),
        ),
    ]
