# Generated by Django 5.1.2 on 2025-01-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateur', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
