# Generated by Django 5.1.2 on 2025-01-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateur', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='confirmation_password',
            field=models.CharField(default=1245, max_length=128),
            preserve_default=False,
        ),
    ]
