# Generated by Django 5.1.2 on 2025-01-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateur', '0004_utilisateur_confirmation_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='confirmation_password',
            field=models.CharField(max_length=50),
        ),
    ]
