# Generated by Django 5.1.2 on 2025-02-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateur', '0005_alter_utilisateur_confirmation_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('Centre', 'Centre'), ('Parrain', 'Parrain'), ('Visiteur', 'Visiteur')], default='Sélectionner', max_length=25),
        ),
    ]
