# Generated by Django 5.1.2 on 2025-02-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUtilisateur', '0006_alter_utilisateur_type_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('Centre', 'Centre'), ('Parrain', 'Parrain')], default='Sélectionner', max_length=25),
        ),
    ]
